success_stories_research_task: ### INCLUIR LOS PARAMETROS DE ENTRADA
  description: >
    Conduct a comprehensive web search to identify success stories of digital technology implementations
    that meet all the following criteria:
    - Must be recent cases (preferably from the last 3 years)
    - Minimum success stories found that meet all the requirements: {stories_number}
    - Technology or kind of digital solution implemented: {technology}
    - Socpe of the process where digital solutions have been implemented: {process_scope}
    - Sector of the company where the digital solutions have been implemented: {company_sector}
    - Country where the digital solution have been implemented: {company_country}    
    Make sure to validate the credibility of sources and cross-reference information when possible.
  expected_output: >
    A structured list of success stories containing:
    - Short description: Short description of the success story
    - URL: URL where the success story is described
    - Company: Name of the implementing company
    - Integrator: list of software integrators names, if found
    - Software Manufacturer: list of software manufacturers names, if found.
    - Valid: true or false. If the success story meet all requiered criteria. 
    - Full article: the full article where the success story is decribed
      
    Make sure that there are not duplicated success stories.

  agent: project_manager
