success_stories_research_task: ### INCLUIR LOS PARAMETROS DE ENTRADA
  description: >
    Conduct a comprehensive web search to identify success stories of digital technology implementations
    that meet the following criteria:
    - Must be recent cases (preferably from the last 3 years)
    - Must include specific details about the technology implemented
    - Must specify the business sector and country of the implementing company
    - Must describe the scope and area of application
    - Must provide quantifiable results or benefits
    Make sure to validate the credibility of sources and cross-reference information when possible.
  expected_output: >
    A structured list of success stories containing:
    - Name of the implementing company
    - Country of implementation
    - Business sector
    - Technology implemented
    - Scope and area of application
    - Key benefits and results achieved
    - Implementation timeframe
    - Source URL and date of publication
    Each story should be presented in a clear, standardized format for easy validation.
  agent: project_manager
